### ISSUE TITLE
Implement dark mode on all screens on MainStack

### ISSUE THREAD

**Issue by LucientZ** [TAMUSHPE/MobileApp#105]
## Overview
Darkmode is a setting that a user can select which will make the entire app use a dark color palette instead of a light one. This can both save on power and be less straining on a user's eyes. Some people also just find a darker color palette more appealing.

## Tasks
- [x] Add darker colors to all screens in and nested in MainStack if darkmode setting is set to true for the user.
- [x] Ensure the colors persist even if the user logs out and logs back in.
- [x] Make sure these changes are saved. This should already be implemented, so only verification is required. (You can do this by making another account, switching to it, and switching back)

## Screen Groups
- [x] Settings Screens
- [x] Leaderboard
- [x] User Profiles
- [x] Involvement
- [x] Event Creation
- [x] Event Information

**Comment by JasonIsAzn** [comment]
This is almost done except for admin screens. 
The dark mode for admin screens will be done along with #397
