### ISSUE TITLE
Create Unit Tests

### ISSUE THREAD

**Issue by LucientZ** [TAMUSHPE/MobileApp#106]
# Overview

Eventually, we will want to develop unit tests to ensure our code runs the way we want it to and to prevent it from being completely broken by accident in the future. This will be super useful as we develop more features that aren't directly visible to the user (eg. querying google-sheets/firebase, helper functions, data handling, etc).

React Native's recommended testing framework is Jest, so we should use that for our unit tests. I'm not assigning this to a milestone yet since this will require some planning for a testing folder structure, so this issue will require some discussion.

See:
- https://jestjs.io/docs/tutorial-react
- https://reactnative.dev/docs/testing-overview

# Tasks
- [x] Add Jest dev-dependency to project
- [x] Setup testing directory structure
- [x] Create tests for both component rendering and various functions in `./src/`
