### ISSUE TITLE
events and points mangament system

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#111]
## Overview
This issue will develop a new feature on the mobile application: **events and points managment system**. This involves a heavy planning phase, followed by executing the plan. In general, the implmenetation will start off with a simple event (i..e attending a teach affair meeting.). 

## Tasks
- [x] create an event in events screen
   - [x] categorize an event (assign points) to that event
   - [x] choose set of people to notify (all or committee specific)
   - [x] QR Code generated
   - [x] fill in event details
- [x] view event in a form of a list
- [x] show current number of people in an event 
- [x] update event in it's event screen
- [x] destory event in it's event screen
- [x] sign in verification
    - [x] check if user already signed in 
    - [x] check event end time 
    - [x] log user into event log

## Additional
This is a big issue and wil mostly be seperated into more issues. 

### User Story
As an officer, I want to create an event, so that members can attend and be notified.
As an officer, I want to update an event, so that I can correct my changes.
As an officer, I want to destroy an event, so that I can get rid of it if I made a mistake.
As an officer, I want a QR code generated, so that I can show at my event so members can sign in.
As a member, I want to view events so that I can see the current event
As a member, I want to scan a QR code so that I can recieve points for an event
