### ISSUE TITLE
Event Notification

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#118]
## Overview 
Create a cron job that will notify users that there is an event 1 hour before the events start time.  The user that will be notified should depend on the event type and the user's interest and committee. 

The event type GENERAL_MEETING should notify all users.
The event types STUDY_HOURS, WORKSHOP, VOLUNTEER_EVENT, SOCIAL_EVENT, INTRAMURAL_EVENT should notiify user who have them in their interests list.
If an event has an assoicated committee, then all user's in the committee should be notified.
It's possible for event type to overlap with assoicated committee so do not send multiple notiifcations.
 

### Task
- [x] create a function to send notification based on the event
- [x] schedule this notification to be called 1 hour before event start
- [x] Add method turn on/off notification by default have off

### Additional
This scheduling part of this will require creating a master cron job. Keep in mind that this master cron job should be created to handle general cases for running functions on a schedule

### User Story
As a user, I want to recieved notifications so that I can be reminded of an event.
