### ISSUE TITLE
committee screen revamp

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#132]
## Overview
The committee screen needs to be revamped. Look at figma. 

## Task
- Remove the following: (the content inside will be useful)
    - [x] Committees Slider 
    - [x] Committtes Info 
- [x]  Create component for a list of committees
- [x] Create component for a committee card
- [x] When a committee is selected then navigate to another committee screen

##  User Story
As a user, I would like to view committees, so that I can learn more about them
