### ISSUE TITLE
even more dynamic memberList component.

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#138]
## Overview
I would like to memberList component to be more dynamic for varies filtering system. The current memberlist contains a simple searching feature and list all officer and members. We want to make this component even more complex by moving the filtering system outside(not the search feature) and add an additional input to apply a filter. This way it can be used not only for filtering in members screen (i.e. by major, class year, name, officer etc) but also filtering by users that are whitelist, blacklist, by points, etc.

## Task
- [x] Refactor memberList component by adding a filtering parameter 
- [x] remove any filtering system related things (not including search) the memberList component
- [x] Implement this filtering for member list
