### ISSUE TITLE
Home & featured slide editor changes [DRAFT]

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#155]
### Overview
We will transition the current feature slider to a new design idea. 

### Task
- [ ] create figma desgin 
- [ ] remove current background and dots
- [ ] randomly slide through images on slider after 2 second
- [ ] add shpe and tamu logo with background opacity and slider behind it
- [ ] move sign in component above office hour
- [ ] add SHPE guide below slider
