### ISSUE TITLE
Member Verification System

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#157]
### Overview
A new system to verify members on the application. A user will request to get verifcation badge and submit the appropriate documentations. A officer can go in a confirm the membership

### Task
- [x] user can submit doc
- [x] officer review doc and confirm/deny
- [x] show verification check mark in memberslist

### User Story
As an officer, I want to verify members, so that I know who the real one are.
