### ISSUE TITLE
Knock On Wall: Update Notifcation Message

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#158]
### Overview
The current notification is very basic and simpliy say that "someone at the door."  The title of the notifcation should be "Knock on Wall" and include the user name that pressed the button.  Change both the in-app and background notification.

### Task
- [x] Add user name to notification for knock on wall 
- [x] Improve Notifcation Design/Message
- [x] implement notification message for both in app and when app is running in background

### User Story
As an officer, I would want to know who pressed the button, so that I can expect to see them at the door.
