### ISSUE TITLE
App Usability

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#159]
### Overview 
App usability deals with how user interact with the app. This invovles making sure buttons easily pressed and unintended features throughout the app. This issue will tackle the issue that we have seen throughout the app as of 10/17.

### Task 
- [x] fix firebase permissions for events
- [x] Login text boxes are too small on IOS, make them bigger
- [x] All navigation back buttons are too small, add padding to them
### User Story
As a user, I would like to use to app without running into minior inconviences, so that my expereince is better.
