### ISSUE TITLE
restrictions: detect bad behavior 

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#177]
### Overview
In this app, it is possible for members to abuse certain features like knock on wall and join/leave committee. If this is detected then add them to a blacklist and disable their features

### Task
- [x] detect bad behavior for knock on wall button
- [x] detect bad behavior for committee join/leave button 
- [x] add to whitelist when bad behavior detected
- [x] disable these features if a user is on the whitelist

### User Story
As an Officer, I want the app to detect bad behavior, so the the ingenuity of the app is upheld.
