### ISSUE TITLE
Refactor Committee Editor

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#190]
### Overview
Instead of having hard coded committee, we want more dynamic committee that will be stored in firestore

### Task
- [x] Switch hard coded committee object to firebase
- [x] Deal with all the consequences of the above
- [x] redo committee counting

### User Story
As an admin, I want a more flex committee editor, so that I can freely add/remove my own committees
