### ISSUE TITLE
Enhance UI/UX for registration screen

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#197]
## Overview
Improve the small detail of registration screen such as box size, font, text alignment, etc. Input box suc has Major/Class Year should be drop down so user can't put some random major or class

## Tasks
- [x] Add drop down list for major and class year
- [x] clean up details
- [x] finish style add resume page

### User Story
[Usability] As a user, I want to be able to easily navigate through registration screen, so I can easily create my account
