### ISSUE TITLE
Web: Create Sign-In Page

### ISSUE THREAD

**Issue by AxeFontaine** [TAMUSHPE/MobileApp#206]
## Overview
Make user sign-in page for officers with certain roles

## Tasks
- [x] Connect Firebase auth from mobile app accounts
- [x] Validate account with certain roles
- [x] Make sign-in page as default

## User Story
As an admin, I would like to be able to login, so that I can access our admin tools
