### ISSUE TITLE
Resume confirmation for resume bank

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#208]
## Overview
The resume bank should only contain resumes that are of high quality this means that we want officers to be able to verify people resume to be used on the resume bank. This system will be very similar to member verifcation feature. One major difference is that if a user changes their resume, then we must be more them from the resume bank and they will need to be reverified. 

## Task
- [x] user can upload public version of their resume (i.e. removed phone, address, etc)
- [x] user can request their resume to be public,
- [x] admin can approve/deny request
- [x] add flag to user profile if they're resume is public
- [x] user can remove the public resume
- [x] if user reupload remove their resume from verified and will have to request again

## Additional
This system does not apply to officers, leads, reps since they will autmoically be in the resume bank

### User Story 
As a user, I want access to high quality resumes, so that I'm using good examples for my own resume
