### ISSUE TITLE
Committee CRUD

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#225]
### Overview
This commitee system must be flexible for the officer. There are some committees that run throughout the year, but some committee are only need for a specifc project or semesterly. For example, Technical Affair is a committee that is always open, but the committee that runs SHPEathon event is only during the spring semester. 
This committee system will follow CRUD (Create, Read, Update, Destory) Operations. In addition, we would also want a "Reset" Committee option to reset certain committe information after someone else takes ownership of it.  In the case of Reset, we will keep  committee Name, Color, Icon, or Description. And remove any application links and team members.  While not in the mobile application, on the website have an view with a list of all members in the given committee.

### Task 
- [ ] Ccreate a committee
- [ ] Read 
   - [ ] In specific committee page, list all user in the committee
   - [ ] view all committees
- [ ] Update a committee
- [ ] Delete/Reset a committee

### Additional
These operations are created in the mobile application. View the feature on the mobile application to get a full understanding of how everything works. See files
