### ISSUE TITLE
Web: Secretary Membership Verification Process

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#226]
### Overview
In TAMU-SHPE, to be a complete member you must submit two documents showing proof that you have payed for (1) tamu shirt reciept and (2) shpe national reciept. User on the mobile app can upload documentation where it can then be viewed by an Secretary.  On the website, we want to view all users that submitted proof and allow the secretary to take the appomiate actions.

### Task
- [ ] A view with all user 
- [ ] for each user show two button to view the two documents
- [ ] for each user show approve or deny button
- [ ] After approved or deny perform the appromiate actions needed.

### Additional
The following file contain useful code for this task:
MemberSHPEConfirm.tsx, MemberSHPE.tsx, membership.ts

**Comment by JasonIsAzn** [comment]
will reopen in the future after more progress
