### ISSUE TITLE
Implement event screen designs from figma

### ISSUE THREAD

**Issue by LucientZ** [TAMUSHPE/MobileApp#233]
# Overview

The current event creation screens have a very basic UI implementation that does not fit with the current aesthetic of the app. There are currently designs in Figma which will be implemented.

# Tasks

- [x] Add more screens to the event creation process
- [x] Design the event preview page
- [x] Implement event creation screen designs
- [x] Add a "Currently active" event category
- [x] Move past events to a separate screen
