### ISSUE TITLE
change email and resume to be private by default

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#243]
### Overview
Email and Resume both must initially be private. Allow user to have an option to make there email public. Resume will always be private and is purely used for SHPE to send their resume to companies. These two fields have been assume to be public, so throughout the whole app deal with the consequence of this. 

### Task 
- [ ] Make Email Private
- [x] Make Resume Private
- [x] add isTamuEmail flag  - in the future we may want to keep track of all students
