### ISSUE TITLE
Replace User Data in committee and Event Host with UID

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#244]
### Overview
When a user is added to a committee (i.e. as a officer, head, lead) or creating event (i..e event host). These field are simply the whole publuc user info. While this was initially done to reduce firebase reads, I ignorantly forgot that user can edit their data, which would mean syncing problem. This also could cause problem if user data has some fundamental changes in the future, which can cause incompatiblity with old data in committee/event documents

### Task
- [x] Replace User Publuc Info with just UID for Event Host 
- [x] Where ever needed, fetch user info with UID for Event Host
- [x] Replace head,leads, reps Publuc Info with just UID for Team Member in Committee 
- [x] Where ever needed, fetch head,leads, reps info with UID for Team Member in Committee
