### ISSUE TITLE
In committee data, change member count to a list of member UID 

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#245]
### Overview
The currnet implementation of MemberCount simply increment/decrement the memberCount. Instead we will have a list of UID and get the length. Then implement a display to view all members in a committee in the commitee info screen.

### Task
- [ ] Replace memberCount with list of UID
- [ ] Deal with all consequences of repalcing memberCount with membersList
- [ ] In committee info screen, add a modal that display all members in the committee
