### ISSUE TITLE
Web: Secretary Event Log View

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#247]
### Overview
When an events ends every member points must be verified before they can recieve their points.  Create a Point Verification page that will display all events that have ended and contain event log that has not been verified. In this listing of event display basic information such that Event Name, Sign in points, Sign out point, hourly points, number of event logs.  When a user select an event, display all event log and their data. 
Each event log should display basic information such as total points earned and # hour signed in. The total points value should be adjustable. 
When user verifes that all log are currect, then all log events should be changed to verified and  uploaded to user's data

### Task 
- [ ] Create Points Verification Page and display events (has ended + has not be verified yet)
- [ ] Display all logs for a given event. Allow users to adjust total points
- [ ] Create a "distributing" points button that will adjust all event logs to verified=true and send to user data.

###
As a secertary, I would like to verify points before distributing them to members

**Comment by JasonIsAzn** [comment]
will reopen in the future after more progress
