### ISSUE TITLE
T-Shirt Size in MemberSHPE Tab

### ISSUE THREAD

**Issue by alvarojcamachoh** [TAMUSHPE/MobileApp#254]
### Overview ###

Give the user the ability to upload their t-shirt size when uploading their documents to become a member. After the user selects their shirt size, give admins access to the data. Admins should then be able to check off members who have picked up their shirts. This eliminates the need for the Google Form new members use when signing up to become members. 

### Task ### 

- [ ] Let user pick their desired t-shirt size during uploading to memberSHPE application
- [ ] Let Admins/Officers view users t-shirt sizes and if they have picked up their shirts
- [ ] Let admins check off users who have picked up their shirts
