### ISSUE TITLE
Committee Membership Verification

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#257]
### Overview
Committee can be overloaded with memebers. Some SHPE member will join too many committess and may be overloading themselves. Some committees are also not fully availabile to the public (i.e. app development team or SHPEathon committee)

### Task
- [x] Remove committee info from registration screen and settings screen
- [x] Remove current join/leave and committee count logic
- [x] Add close/open committee flag
- [x] if committee close then allow user to request to join
- [x] if committee open then auto allow user to join
- [x] if user leave committee simply remove their tag (they must resubmit request to join)
- [x] Admin can approve/deny membership

### User Story
As a user, I want to request to join a committee so that I can get invovled with shpe events
