### ISSUE TITLE
Committee Members List

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#281]
### Overview
In the committee info screen, you can see the numbers of members that are in the committee. However it was pointed out that it is more useful to also know who exactly is in the committee. Implement this list and also the UI (i.e. add a button).

### Task 
- [ ] Create a function to fetch a list of member in a specfic committee
- [ ] Display the committee members in a list
- [ ] Add a button to display the list

### User Story
As a User, I want to view a list of member in a specific committee, so I know exactly if someone is in a committee.

### Prereq
- #257
