### ISSUE TITLE
Guest Restricted Access

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#303]
### Task
- [x] restrict event sign in/out to student only (deal with verifcation screen as well)
- [x] knock on wall restrict to student only
- [x] joining committee restrict to student only
- [x] restrict test bank and resume bank to verified members

**Comment by JasonIsAzn** [comment]
CHANGES:
When it comes to restrict test/resume bank we want this to be accessed by verified members only
(see **isMemberVerified** function and usage)
The test and resume bank should also be visible to all users but if they are not verified they create a pop-up indicating that the user must be a member and redirect them to the **memberSHPE** screen
