### ISSUE TITLE
Add description limit for committee, events, and user biography

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#362]
### Overview
There are specifc screens that uses these descriptions or long pieces of text and they are specifically design to not to be scrollable (commitee screen, event screen, and user profile screen). We want to limit the amount of chacters the user inputs.

### Task
- [x] Add limit character 
    - [x] for committee screen
    - [x] for event screen
    - [x] for user profile bio
