### ISSUE TITLE
Admin Dashboard UI

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#397]
### Overview
Admin dashboard need new ui enhancements

### Task
- [x] Design Admin Dashboard
- [x] Implement updated UI
- [x] implement dark mode for admin screens
