### ISSUE TITLE
Pending Event - Backend

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#408]
### Overview
We want an iterative process for points verification. This will be done by verifiy each event one at a time. The secretary will look at the event and need the basic information (i.e. name, event type, points, etc). They will also need to be able to view every person that signed in and/or signed out. Then adjust the total point for that event.

### Task
- [ ] Display basic information of event
- [ ] Display list of all members that logged into the event
- [ ] Display the points earned for each members and allow points to be updated
- [ ] Confirmation button that will mark the verification flag as true in both event collection and user collection
