### ISSUE TITLE
Committee List UI Update

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#428]
### Overview
During the design for the committee list, I did not expect there to be so many committee. We need a better way to organize these committees.
An Idea that I'm thinking about is the filter the committee list by respective officers Title. So we will have a filter that display the title and when a user click on the title like Technical Affairs, the committees technical affair, web dev, app dev, etc will show up.

### Task
- [ ] remove the search bar and implement a filter system
- [ ] Replace head with officer
- [ ] Revamp committee list

**Comment by JasonIsAzn** [comment]
this is a waste of time. If we wnat to do UI update, lets do it another time.
