### ISSUE TITLE
Instagram Points: Usability Improvement

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#551]
### Overview
When allocating points, we want to save the selected users until a submission is made.  If an officer leave the page, then keep their selected users.
In this case, show a confirmation list of users that will have get points before submission is made.
Since we have over 500+ users on the app, loading every user on the list is causing major lag. To prevent this, lets intially load all user's that have previously been allocated points in a default tab called "Previously Posted". 
Then if an officers wishes to visit the "All User" tab to get new members

### Task
- [x] Cache the selected users until a submission is made
- [x] Before submission is made display a scrollable list of all Users
- [x] ~~Create two tabs, one tab for "Previously Posted" and "All Users"~~ Searching requires at least two characters and improve performance

### User Stories
As an officer, I want to have my selection saved so that when i accidently leave the screen my selections are saved
As an officer, I want less lag in the instragram points selection, so that I can smoothly allocate points
As an officer, I want to clearly know who I'm allocating points to so that I can correctly allocate points

**Comment by JasonIsAzn** [comment]
intially i was thinking of having two list one for users that have previously posted and another of all users 
but the list of previously posted users is also really large so it only helps slightly with loading problem. My idea was also that officer could just scroll through this list. But again it's so large they will always just be searching people anyways.

so now my solution is just to the list display only if u enter two more or characters
