### ISSUE TITLE
New Role: Coach

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#553]
### Overview
We need a new role called Coach. There are specific intramural games where coaches have to create their own events. However these coaches are not the same as rep/lead/officers. In the case of coaches they should only be able to create intramural events. 
This may be complicated in backend? so i'm fine with just giving power to coaches to edit all of event collection and on ui side only allow them to create the events.

### Task
- [ ] Create coach role
- [ ] Allow coach role to only change event collection
- [ ] Coach can only create intramural events ui side.

### User Stories

- As an officer, I want to delegate the IM event creation process to my respective team coaches for the IM teams so that I am not overwhelmed with work.
