### ISSUE TITLE
Sanitize all user inputs when creating and modifying account

### ISSUE THREAD

**Issue by LucientZ** [TAMUSHPE/MobileApp#73]
# Overview

Currently, pretty much any and all strings are accepted in the creation of a user's account (minus character limits). Some fields need to be sanitized including:
- Display name (Should be unique. This is not currently enforced)
- Class year (This could be changed to a dropdown since there are only a certain amount of these which should be possible)
- Other future information including tamu email since we're going to be adding this as a field in the future so people are able to use their personal emails for the account.

Sanitization will mainly involve creating some regex checks that ensure data matches patterns that should be enforced. 

# Tasks
- [x] Sanitize TAMU email
- [x] Sanitize user email before account creation (catch email issues sending firebase creation request)
- [x] Sanitize image blobs (try to ensure correct file format)
- [x] Sanitize resume blobs
